apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: counter-app-service-monitor
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 15s
      port: web
  selector:
    matchLabels:
      app: counter-app
