apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: counter-app-pod-monitor
  labels:
    app: counter-app
spec:
  selector:
    matchLabels:
      app: counter-app
  podMetricsEndpoints:
    - port: http
#      path: /metrics
#      scheme: http
#      interval: 15s
