apiVersion: v1
kind: Service
metadata:
  name: counter-app
  labels:
    app: counter-app
spec:
  type: ClusterIP
  selector:
    app: counter-app
  ports:
    - port: 8080
      targetPort: 8000
      name: web
