# No alertmanager for this demo
alertmanager:
  enabled: false

# This configuration means all ServiceMonitors in the namespsace will be picked up
# Use with caution!
prometheus:
  prometheusSpec:
    # See https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
    # Ignore empty/null serviceMonitorSelector, do not use default values
    serviceMonitorSelectorNilUsesHelmValues: false
    # select all service monitors
    serviceMonitorSelector: {}
    # in all namespaces
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false # TODO: check
#    podMonitorNamespaceSelector: {}
#    podMonitorSelector: {}
    probeSelectorNilUsesHelmValues: false

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
