# No alertmanager for this demo
alertmanager:
  enabled: false

# This configuration means all ServiceMonitors in the namespsace will be picked up
# Use with caution!
prometheus:
  prometheusSpec:
    # See https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
#    serviceMonitorSelector:
#      matchLabels:
#        team: operations
#    ruleSelectorNilUsesHelmValues: false
##    podMonitorNamespaceSelector: {}
##    podMonitorSelector: {}
#    probeSelectorNilUsesHelmValues: false

grafana:
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
